import math
def leap_year():
    print("TO DO")

coeficiente_A = float(input("Ingrese el coeficiente A: "))
coeficiente_B = float(input("Ingrese el coeficiente B: "))
coeficiente_X1 = float(input("Ingrese el coeficiente X1: "))
coeficiente_X2 = float(input("Ingrese el coeficiente X2: "))
print(f"El coeficiente A de la ecuacion de la recta es {coeficiente_A}")
print(f"El coeficiente B de la ecuacion de la recta es {coeficiente_B}")
print(f"El coeficiente X1 de la ecuacion de la recta es {coeficiente_X1}")
print(f"El coeficiente X2 de la ecuacion de la recta es {coeficiente_X2}")
print("")
print("para la siguiente ecuacion")
print(f"\tY= {coeficiente_A}X + {coeficiente_B}")
print("")
print("dado los siguientes puntos")
print(f"\t P1({coeficiente_X1}, {coeficiente_X1 * coeficiente_A + coeficiente_B})")
print(f"\t P2({coeficiente_X2}, {coeficiente_X2 * coeficiente_A + coeficiente_B})")
print("")
print(f"distancia entre ellos es: {math.sqrt(((coeficiente_X2 - coeficiente_X1)**2 + ((coeficiente_X2 * coeficiente_A + coeficiente_B) - (coeficiente_X1 * coeficiente_A + coeficiente_B))**2))}")
